spring:
  datasource:
    #url: jdbc:mysql://45.93.1.5:3306/fire?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: 123456
    url: jdbc:mysql://172.30.92.199:3306/weydb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: weyor
    password: we1123
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
        useInformationSchema: true
